version: '3.8'

services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    expose:
      - "3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app2:
    build: .
    environment:
      - APP_NAME=App2
    expose:
      - "3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app3:
    build: .
    environment:
      - APP_NAME=App3
    expose:
      - "3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app1:
        condition: service_started
      app2:
        condition: service_started
      app3:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge