version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    expose:
      - "3000"  # Exposed internally to other containers

  app2:
    build: .
    environment:
      - APP_NAME=App2
    expose:
      - "3000"  # Exposed internally to other containers

  app3:
    build: .
    environment:
      - APP_NAME=App3
    expose:
      - "3000"  # Exposed internally to other containers

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose HTTP port 80 to host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx config
    depends_on:
      - app1
      - app2
      - app3