version: '3.8'

services:
  app1:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App1
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  app2:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App2
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  app3:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=App3
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/images:ro
    depends_on:
      - app1
      - app2
      - app3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M